repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=79]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--ignore=E501,E203,W605,T001,B008,W503,B006,B007,E741,E266,E262']
        additional_dependencies: [flake8-bugbear, flake8-print]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      # - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      # - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: trailing-whitespace
