# TODO: Change this to case-relevant examples
EXAMPLES = {
    "manufacturing": [
        'For example, given a video with a "title" of "Eighty percent chance the cage won\'t be escaped, maybe eaten but no blood seen, continue the search for biubiu, do you have any methods to find the hamster?", "category" as "Animals", "ocr" as "Today, biubiu is missing, there\'s no sign of biubiu anywhere, and the cage wasn\'t closed last night.", "asr" as "Today, I found that BB is missing, there\'s no sign of BB anywhere, the cage wasn\'t closed last night, it must have escaped, but the cage is quite high, so it\'s unlikely to escape, let\'s keep looking in section B." The {} generated robot infers a reasonable "{}" as "Hamster pseudo-hibernation, hamster feigning death, hamster missing, hamster hibernation.".',
        'For example, given a video with a "title" of "Can\'t draw anime legs? Let\'s see if your drawn legs are correct #Anime #HandDrawingTutorial #HandDrawing #FutureDesigner", "category" as "Talent", "ocr" as "Can\'t draw good-looking manga legs, learn to draw legs like this for better results.", "asr" as "So, living on another small road in Wan San, do I look like it? I walk like this every day and forget that I\'m in a fairyland. I have to tell the world about it, so living on another small road in Wan San, do I look like it? I walk like this every day and forget. The {} generated robot infers a reasonable "{}" as "Anime teacher, anime character drawing tutorial, how to draw manga legs, beginner drawing tutorial.".',
        'For example, given a video with a "title" of "Daily life hacks #LifeHacks #InnerMongoliaSpecialty", "category" as "Health, Lifestyle", "ocr" as "Life hacks tricks", "asr" as "These little tricks, if you know them, you\'ve hit the jackpot. It\'s easy to bend when inserting a straw, just seal the top with your thumb, and you can easily remove the hair from the drain by cutting the straw with scissors, so you can keep the spring in the middle and seal the unfinished yogurt with a straw, which is very practical. Follow me for more life experiments.". The {} generated robot infers a reasonable "{}" as "Daily life hacks, life tips, complete guide to hacks.".',
        'For example, given a video with a "title" of "Cheapest Changan car in the Chang\'an series, starting at 40,000, many people don\'t think much of it, but I know a car is just a means of transportation, what else do you need for face? #ChanganAutomobile", "category" as "Cars", "ocr" as "The cheapest car in the Changan series", "asr" as "I don\'t deny that there is still a certain gap between domestic and joint venture cars now, but it\'s true that they\'ve allowed us to drive a car for 50,000, an MPV for 100,000, and a large seven-seater for 150,000.". The {} generated robot infers a reasonable "{}" as "Changan car price, cheapest Changan car, new Changan car".',
        'For example, given a video with a "title" of "Whole-house embedded subwoofer, mainly because I really love this projector 💕 ", "category" as "Real Estate, Home", "ocr" as "42 square meters, one bedroom, one living room small layout", "asr" as "Look, the distant lights are shining. You, alone, bow your head on the road. The bigger the city, the more anxious and yearning it becomes, the longer it gets. I wish you a safe journey with too much luggage. Forget all the initial smiles. Time makes us fragile, but strong, let me sing to you with love. I wish I could sing with you more often. Tell you about the scenery of life.". The {} generated robot infers a reasonable "{}" as "Small layout decoration, one bedroom, one living room decoration, decoration effect picture".',
    ],
    "Education": [],
}


# TODO: Change this to case-relevant examples
EXAMPLES_TAGS = [
    [
        "Hamster Maze",
        "Hamster Biting",
        "Mouse Catching",
        "Removing Lice",
        "Cat and Mouse",
        "Cat Searching",
        "Lip Hair Removal",
        "Animal Life",
        "Animal Reproduction",
        "Mouse Eradication",
        "Cage",
        "Mouse Control",
        "Animal Science",
        "Animal Mukbang",
        "Animal Production",
        "Wire Cage Fishing",
        "Pet Cage",
        "Animal Education",
        "Animal PK",
        "Bait Atomization",
        "Hamster Illness",
        "Cage Training",
        "Golden Silk Bear Cage Cleaning",
        "Cage Cleaning",
        "Animal",
        "Animal Show",
        "Hamster Cage",
        "Transparent Cage",
        "Hamster Exercise",
        "Removing Whiskers",
        "Piglet Diarrhea",
        "Soup Dumplings",
        "Animal Ecology",
        "Cockroach Elimination",
    ],
    [
        "Forget-Me-Not Bouquet",
        "Secrets to Beautiful Legs",
        "Leg Shape Correction",
        "Learning Simple Sketches",
        "Drawing Tutorials",
        "Self-Taught Drawing",
        "Personal Talents",
        "Leg Slimming Exercises",
        "Entertainment Talents",
        "Quick Talents",
        "Easy Drawing Techniques",
        "Hell Camp Training",
        "Talent Showcase",
        "Mini World",
        "Talent Expression",
        "Talent Competitors",
        "Simple Drawing Skills",
        "Paper Art Talents",
        "Perfect Leg Shape",
        "Leg Slimming Plans",
        "Mountain Bike Downhill",
        "Talents",
        "Leg Slimming Workouts",
        "Cartoon Drawing Tutorials",
        "Leg Health",
        "Anime Character Drawing Tutorials",
        "Yo-Yo Road Asia Pole",
        "High Heel Sketching Tutorials",
        "Leg Shape Improvement",
        "Yemo",
        "Talent Projects",
        "Leg Shape Assessment",
        "Drawing Techniques",
        "Extreme Pole",
        "Creative Talents",
        "Dress Drawing Techniques",
        "Beautiful Legs",
        "Hand Demon",
        "Weilong Magic Yuba Refreshing",
        "Bai Li Xuan Ce",
    ],
    [
        "Bending Techniques",
        "Pruning Techniques",
        "Women's Life Hacks",
        "Life Hacks",
        "Life Tips",
        "Finger Guard Bandage",
        "Useful Tips",
        "Life Health",
        "Rebar Tying Techniques",
        "Pear Tree Pruning Techniques",
        "Life Conditioning",
        "Wire Breakage Remover",
        "Nail Clipping Techniques",
        "Health",
        "Car Hacks",
        "Summer Life Hacks",
        "Health Tips",
        "Scissor Surface",
        "Steel Wire Rope Sleeve",
        "Health and Wellness",
        "Life Tips",
        "Daily Life",
        "Wellness Life",
        "Home Life Hacks",
        "Physiological Health",
        "Creative Life Hacks",
        "Life Hacks",
        "Daily Tips",
        "Health and Wellness",
        "Learning Tips",
        "Positive Life Hacks",
        "Mobile Phone Hacks",
        "Manual Pipe Bender",
        "Life Wellness",
        "Life",
        "DIY Hacks",
        "Fitness Life",
    ],
    [
        "Affordable Cars",
        "Car Accessories",
        "Luxury Car Recommendations",
        "Entry-Level Luxury Cars",
        "Car Driving Test",
        "Best Value Cars",
        "Budget Sports Cars",
        "Luxury Car Market",
        "Car Accessories",
        "Entry-Level SUVs",
        "Domestic Luxury Cars",
        "Luxury Seven-Seater SUVs",
        "Car Manufacturing",
        "SUVs Under 100K",
        "Car Electronics",
        "Car Delivery",
        "Cheapest Vans",
        "Wei Cars",
        "High-Value Car Brands",
        "SUVs",
        "Affordable SUVs",
        "Economical Practical Cars",
        "Car DIY",
        "Seven-Seater Car Recommendations",
        "Affordable and Good Cars",
        "High-Value SUVs",
        "Cars",
        "World's Most Expensive Cars",
        "High-Value Sedan Recommendations",
        "High-Value Sports Cars",
        "Luxury SUV Buying Guide",
        "Luxury Rides",
    ],
    [
        "In-Car Audio Systems",
        "Real Estate and Home",
        "Housing Layouts",
        "Audio Tuning",
        "Car Audio",
        "Single-Floor House Design",
        "Peaceful Moments",
        "JBL Audio",
        "Smart Speakers",
        "Small Kitchen in Small Homes",
        "Small Home Furniture",
        "Scenic Roads",
        "Small Bathroom Design for Small Homes",
        "Small Home Renovation",
        "Nordic Home Decor",
        "Home Products",
        "Youthful Moments",
        "Small Space Utilization in Small Homes",
        "Home Electricals",
        "Life Journey",
        "Audio Systems",
        "Home DIY",
        "100 Square Meter Renovation",
        "Night Driving Light Operations",
        "Car Audio Installation",
        "Small Homes",
        "Home Building Materials",
        "Practical Home",
        "Long-Distance Driving",
        "Youthful Forever",
        "Chasing Dreams",
        "BOSE Audio",
        "Time Passing By",
        "Home Life",
        "Audio System Upgrades",
        "Campus Memories",
        "Home Clothing",
        "Home Living",
        "Audio System Configuration",
        "Three-Bedroom Two-Living Room Renovation",
    ],
]
